# Generated by Django 4.2 on 2023-05-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фонове зображення'),
        ),
    ]
